# netlify.toml - default configuration example
[build]
command = "npm run build"
publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
